# Generated by Django 4.2.7 on 2023-11-26 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('EduInstitutionID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('ResumeID', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Employer', 'Работодатель'), ('JobSeeker', 'Соискатель'), ('Admin', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('VacancyID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('EmployerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='riddles.user')),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('JobSeekerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='riddles.user')),
                ('birthdate', models.DateField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('ApplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Accepted', 'Принят'), ('Rejected', 'Отклонен'), ('Pending', 'В рассмотрении')], max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.user')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeApplication',
            fields=[
                ('ApplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Accepted', 'Принят'), ('Rejected', 'Отклонен'), ('Pending', 'В рассмотрении')], max_length=20)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.resume')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('MessageID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='riddles.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='riddles.user')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('EducationID', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('edu_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.educationalinstitution')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.resume')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.employer'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.jobseeker'),
        ),
    ]
