# Generated by Django 4.2.7 on 2023-11-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0003_alter_user_email_alter_user_password_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
