# Generated by Django 4.2.7 on 2023-12-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
